Finished update
- Added mobile section for work experience
- Corrected minor typos/missing information

Error: Hosting service does not display the experience section correctly on the desktop. The CSS for that section does not take effect for some reason. The mobile website works perfectly.

html file works fine when opened.